[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Redirects for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
